// Generated by js_of_ocaml 2.5
(function(joo_global_object_B_)
   {"use strict";
    var
     num_254_V_=254,
     num_224_U_=224,
     num_250_T_=250,
     num_1024_m_=1024,
     num_57343_Q_=57343,
     num_512_S_=512,
     num_128_f_=128,
     str_e_="",
     str_file_already_abr_w_=" : file already exists",
     num_56320_N_=56320,
     num_240_O_=240,
     num_2048_P_=2048,
     num_248_d_=248,
     str_M_="/",
     str_fd_R_="fd ";
     /*<<stdlib.js 47 0>>*/ function raw_array_append_one_aX_(a_a_,x_b_)
     {var
        /*<<stdlib.js 48 8>>*/ l_e_=a_a_.length,
        /*<<stdlib.js 49 8>>*/ b_d_=new Array(l_e_+1),
        /*<<stdlib.js 50 8>>*/ i_c_=0;
       /*<<stdlib.js 51 2>>*/ for(;i_c_<l_e_;i_c_++)b_d_[i_c_]=a_a_[i_c_];
      b_d_[i_c_]=x_b_;
       /*<<stdlib.js 53 2>>*/ return b_d_ /*<<stdlib.js 54 0>>*/ }
     /*<<stdlib.js 23 0>>*/ function raw_array_sub_C_(a_a_,i_b_,l_c_)
     { /*<<stdlib.js 24 8>>*/ var b_e_=new Array(l_c_);
       /*<<stdlib.js 25 2>>*/ for
       ( /*<<stdlib.js 25 12>>*/ var j_d_=0;j_d_<l_c_;j_d_++)
       b_e_[j_d_]=a_a_[i_b_+j_d_];
       /*<<stdlib.js 26 2>>*/ return b_e_ /*<<stdlib.js 27 0>>*/ }
     /*<<stdlib.js 59 0>>*/ function caml_call_gen_o_(f_c_,args_b_)
     { /*<<stdlib.js 60 2>>*/ if(f_c_.fun)
        /*<<stdlib.js 61 4>>*/ return  /*<<stdlib.js 61 11>>*/ caml_call_gen_o_
               (f_c_.fun,args_b_);
      var
        /*<<stdlib.js 62 8>>*/ n_a_=f_c_.length,
        /*<<stdlib.js 63 14>>*/ argsLen_d_=args_b_.length,
        /*<<stdlib.js 64 8>>*/ d_e_=n_a_-argsLen_d_;
       /*<<stdlib.js 65 2>>*/ if(d_e_==0)
        /*<<stdlib.js 66 4>>*/ return  /*<<stdlib.js 66 11>>*/ f_c_.apply
               (null,args_b_);
      else
        /*<<stdlib.js 67 7>>*/ if(d_e_<0)
         /*<<stdlib.js 68 4>>*/ return  /*<<stdlib.js 68 11>>*/ caml_call_gen_o_
                ( /*<<stdlib.js 68 25>>*/ f_c_.apply
                  (null,
                    /*<<stdlib.js 69 33>>*/ raw_array_sub_C_(args_b_,0,n_a_)),
                  /*<<stdlib.js 70 25>>*/ raw_array_sub_C_
                  (args_b_,n_a_,argsLen_d_-n_a_));
       else
         /*<<stdlib.js 72 4>>*/ return function(x_a_)
         { /*<<stdlib.js 72 25>>*/ return  /*<<stdlib.js 72 32>>*/ caml_call_gen_o_
                  (f_c_,
                    /*<<stdlib.js 72 49>>*/ raw_array_append_one_aX_
                    (args_b_,x_a_)) /*<<stdlib.js 72 11>>*/ } /*<<stdlib.js 73 0>>*/ }
     /*<<stdlib.js 114 0>>*/ function caml_raise_with_arg_aK_(tag_a_,arg_b_)
     { /*<<stdlib.js 114 42>>*/ throw [0,tag_a_,arg_b_] /*<<stdlib.js 114 63>>*/ }
     /*<<mlString.js 50 0>>*/ function caml_str_repeat_aN_(n_a_,s_b_)
     { /*<<mlString.js 51 2>>*/ if(s_b_.repeat)
        /*<<mlString.js 51 16>>*/ return  /*<<mlString.js 51 23>>*/ s_b_.repeat
               (n_a_);
      var
        /*<<mlString.js 52 8>>*/ r_c_=str_e_,
        /*<<mlString.js 52 16>>*/ l_d_=0;
       /*<<mlString.js 53 2>>*/ if(n_a_==0)
        /*<<mlString.js 53 14>>*/ return r_c_;
       /*<<mlString.js 54 2>>*/ for(;;)
        /*<<mlString.js 54 10>>*/ { /*<<mlString.js 55 4>>*/ if(n_a_&1)
         r_c_+=s_b_;
        n_a_>>=1;
         /*<<mlString.js 57 4>>*/ if(n_a_==0)
          /*<<mlString.js 57 16>>*/ return r_c_;
        s_b_+=s_b_;
        l_d_++;
         /*<<mlString.js 60 4>>*/ if(l_d_==9)
          /*<<mlString.js 60 16>>*/  /*<<mlString.js 61 6>>*/ s_b_.slice(0,1)} /*<<mlString.js 66 0>>*/ }
     /*<<mlString.js 70 0>>*/ function caml_subarray_to_string_A_
     (a_a_,i_b_,len_c_)
     { /*<<mlString.js 71 8>>*/ var f_d_=String.fromCharCode;
       /*<<mlString.js 72 2>>*/ if(i_b_==0&&len_c_<=4096&&len_c_==a_a_.length)
        /*<<mlString.js 72 48>>*/ return  /*<<mlString.js 72 55>>*/ f_d_.apply
               (null,a_a_);
       /*<<mlString.js 73 8>>*/ var s_f_=str_e_;
       /*<<mlString.js 74 2>>*/ for
       (;0<len_c_;i_b_+=num_1024_m_,len_c_-=num_1024_m_)
       s_f_+=
        /*<<mlString.js 75 9>>*/ f_d_.apply
        (null,
          /*<<mlString.js 75 24>>*/ raw_array_sub_C_
          (a_a_,i_b_, /*<<mlString.js 75 43>>*/ Math.min(len_c_,num_1024_m_)));
       /*<<mlString.js 76 2>>*/ return s_f_ /*<<mlString.js 77 0>>*/ }
     /*<<mlString.js 249 0>>*/ function caml_convert_string_to_bytes_p_(s_a_)
     { /*<<mlString.js 251 2>>*/ if(s_a_.t==2)
       s_a_.c+=
        /*<<mlString.js 252 11>>*/ caml_str_repeat_aN_
        (s_a_.l-s_a_.c.length,"\0");
      else
       s_a_.c=
        /*<<mlString.js 254 10>>*/ caml_subarray_to_string_A_
        (s_a_.c,0,s_a_.c.length);
      s_a_.t=0 /*<<mlString.js 256 0>>*/ }
     /*<<mlString.js 162 0>>*/ function caml_is_ascii_Z_(s_a_)
     { /*<<mlString.js 164 2>>*/ if(s_a_.length<24)
        /*<<mlString.js 164 21>>*/ { /*<<mlString.js 166 4>>*/ for
         ( /*<<mlString.js 166 15>>*/ var i_b_=0;i_b_<s_a_.length;i_b_++)
          /*<<mlString.js 166 39>>*/ if
          ( /*<<mlString.js 166 43>>*/ s_a_.charCodeAt(i_b_)>127)
           /*<<mlString.js 166 66>>*/ return false;
         /*<<mlString.js 167 4>>*/ return true}
      else
        /*<<mlString.js 169 4>>*/ return ! /*<<mlString.js 169 12>>*/ /[^\x00-\x7f]/.test
               (s_a_) /*<<mlString.js 170 0>>*/ }
     /*<<mlString.js 115 0>>*/ function caml_utf16_of_utf8_aT_(s_a_)
     { /*<<mlString.js 116 2>>*/ for
       (var
          /*<<mlString.js 116 13>>*/ b_l_=str_e_,
          /*<<mlString.js 116 21>>*/ t_d_=str_e_,
         c_i_,
         c1_h_,
         c2_j_,
         v_b_,
          /*<<mlString.js 116 43>>*/ i_c_=0,
          /*<<mlString.js 116 50>>*/ l_k_=s_a_.length;
        i_c_<
        l_k_;
        i_c_++)
        /*<<mlString.js 116 74>>*/ {c1_h_=
         /*<<mlString.js 117 9>>*/ s_a_.charCodeAt(i_c_);
         /*<<mlString.js 118 4>>*/ if(c1_h_<num_128_f_)
          /*<<mlString.js 118 19>>*/ { /*<<mlString.js 119 6>>*/ for
           ( /*<<mlString.js 119 17>>*/ var j_g_=i_c_+1;
            j_g_<
            l_k_&&
            (c1_h_= /*<<mlString.js 119 43>>*/ s_a_.charCodeAt(j_g_))<
            num_128_f_;
            j_g_++)
            /*<<mlString.js 119 72>>*/ ;
           /*<<mlString.js 120 6>>*/ if(j_g_-i_c_>num_512_S_)
            /*<<mlString.js 120 23>>*/ { /*<<mlString.js 120 25>>*/ t_d_.substr
             (0,1);
            b_l_+=t_d_;
            t_d_=str_e_;
            b_l_+= /*<<mlString.js 120 62>>*/ s_a_.slice(i_c_,j_g_)}
          else
           t_d_+= /*<<mlString.js 121 16>>*/ s_a_.slice(i_c_,j_g_);
           /*<<mlString.js 122 6>>*/ if(j_g_==l_k_)
            /*<<mlString.js 122 18>>*/ break;
          i_c_=j_g_}
        v_b_=1;
         /*<<mlString.js 126 4>>*/ if
         (++i_c_<
          l_k_&&
          ((c2_j_= /*<<mlString.js 126 29>>*/ s_a_.charCodeAt(i_c_))&-64)==
          num_128_f_)
          /*<<mlString.js 126 62>>*/ {c_i_=c2_j_+(c1_h_<<6);
           /*<<mlString.js 128 6>>*/ if(c1_h_<num_224_U_)
            /*<<mlString.js 128 21>>*/ {v_b_=c_i_-12416;
             /*<<mlString.js 130 8>>*/ if(v_b_<num_128_f_)v_b_=1}
          else
            /*<<mlString.js 131 13>>*/ {v_b_=2;
             /*<<mlString.js 133 8>>*/ if
             (++i_c_<
              l_k_&&
              ((c2_j_= /*<<mlString.js 133 33>>*/ s_a_.charCodeAt(i_c_))&-64)==
              num_128_f_)
              /*<<mlString.js 133 66>>*/ {c_i_=c2_j_+(c_i_<<6);
               /*<<mlString.js 135 10>>*/ if(c1_h_<num_240_O_)
                /*<<mlString.js 135 25>>*/ {v_b_=c_i_-925824;
                 /*<<mlString.js 137 12>>*/ if
                 (v_b_<num_2048_P_||v_b_>=55295&&v_b_<57344)
                 v_b_=2}
              else
                /*<<mlString.js 138 17>>*/ {v_b_=3;
                 /*<<mlString.js 140 14>>*/ if
                 (++i_c_<
                  l_k_&&
                  ((c2_j_= /*<<mlString.js 140 39>>*/ s_a_.charCodeAt(i_c_))&
                   -64)==
                  num_128_f_&&
                  c1_h_<
                  245)
                  /*<<mlString.js 141 31>>*/ {v_b_=c2_j_-63447168+(c_i_<<6);
                   /*<<mlString.js 143 16>>*/ if(v_b_<65536||v_b_>1114111)
                   v_b_=3}}}}}
         /*<<mlString.js 149 4>>*/ if(v_b_<4)
          /*<<mlString.js 149 15>>*/ {i_c_-=v_b_;t_d_+="\ufffd"}
        else
          /*<<mlString.js 152 11>>*/ if(v_b_>65535)
          t_d_+=
           /*<<mlString.js 153 11>>*/ String.fromCharCode
           (55232+(v_b_>>10),num_56320_N_+(v_b_&1023));
         else
          t_d_+= /*<<mlString.js 155 11>>*/ String.fromCharCode(v_b_);
         /*<<mlString.js 156 4>>*/ if(t_d_.length>num_1024_m_)
          /*<<mlString.js 156 25>>*/ { /*<<mlString.js 156 26>>*/ t_d_.substr
           (0,1);
          b_l_+=t_d_;
          t_d_=str_e_}}
       /*<<mlString.js 158 2>>*/ return b_l_+t_d_ /*<<mlString.js 159 0>>*/ }
     /*<<mlString.js 174 0>>*/ function caml_to_js_string_aS_(s_a_)
     { /*<<mlString.js 175 2>>*/ switch(s_a_.t)
       {case 9: /*<<mlString.js 177 4>>*/ return s_a_.c;
        default:
          /*<<mlString.js 179 4>>*/ caml_convert_string_to_bytes_p_(s_a_);case 0:
          /*<<mlString.js 181 4>>*/ if
          ( /*<<mlString.js 181 8>>*/ caml_is_ascii_Z_(s_a_.c))
           /*<<mlString.js 181 28>>*/ {s_a_.t=9;
            /*<<mlString.js 183 6>>*/ return s_a_.c}
         s_a_.t=8;
        case 8:
          /*<<mlString.js 187 4>>*/ return  /*<<mlString.js 187 11>>*/ caml_utf16_of_utf8_aT_
                 (s_a_.c)
        } /*<<mlString.js 189 0>>*/ }
     /*<<mlString.js 242 0>>*/ function MlString_h_
     (tag_a_,contents_b_,length_c_)
     {this.t=tag_a_;
      this.c=contents_b_;
      this.l=length_c_ /*<<mlString.js 244 0>>*/ }
    MlString_h_.prototype=
    {toString:
     function()
      { /*<<mlString.js 245 43>>*/ return  /*<<mlString.js 245 50>>*/ caml_to_js_string_aS_
               (this) /*<<mlString.js 245 32>>*/ }};
     /*<<mlString.js 300 0>>*/ function caml_new_string_c_(s_a_)
     { /*<<mlString.js 300 31>>*/ return new MlString_h_(0,s_a_,s_a_.length) /*<<mlString.js 300 66>>*/ }
     /*<<stdlib.js 118 0>>*/ function caml_raise_with_string_ab_
     (tag_a_,msg_b_)
     { /*<<stdlib.js 119 2>>*/ caml_raise_with_arg_aK_
       (tag_a_, /*<<stdlib.js 119 28>>*/ caml_new_string_c_(msg_b_)) /*<<stdlib.js 120 0>>*/ }
     /*<<stdlib.js 92 21>>*/ var caml_global_data_g_=[0];
     /*<<stdlib.js 158 0>>*/ function caml_invalid_argument_y_(msg_a_)
     { /*<<stdlib.js 159 2>>*/ caml_raise_with_string_ab_
       (caml_global_data_g_[4],msg_a_) /*<<stdlib.js 160 0>>*/ }
     /*<<int64.js 39 0>>*/ function caml_int64_compare_aC_(x_a_,y_b_)
     {var
        /*<<int64.js 40 9>>*/ x3_c_=x_a_[3]<<16,
        /*<<int64.js 41 9>>*/ y3_d_=y_b_[3]<<16;
       /*<<int64.js 42 2>>*/ if(x3_c_>y3_d_) /*<<int64.js 42 15>>*/ return 1;
       /*<<int64.js 43 2>>*/ if(x3_c_<y3_d_) /*<<int64.js 43 15>>*/ return -1;
       /*<<int64.js 44 2>>*/ if(x_a_[2]>y_b_[2])
        /*<<int64.js 44 19>>*/ return 1;
       /*<<int64.js 45 2>>*/ if(x_a_[2]<y_b_[2])
        /*<<int64.js 45 19>>*/ return -1;
       /*<<int64.js 46 2>>*/ if(x_a_[1]>y_b_[1])
        /*<<int64.js 46 19>>*/ return 1;
       /*<<int64.js 47 2>>*/ if(x_a_[1]<y_b_[1])
        /*<<int64.js 47 19>>*/ return -1;
       /*<<int64.js 48 2>>*/ return 0 /*<<int64.js 49 0>>*/ }
     /*<<stdlib.js 364 0>>*/ function caml_int_compare_aD_(a_a_,b_b_)
     { /*<<stdlib.js 365 2>>*/ if(a_a_<b_b_)
        /*<<stdlib.js 365 13>>*/ return -1;
       /*<<stdlib.js 365 26>>*/ if(a_a_==b_b_)
        /*<<stdlib.js 365 38>>*/ return 0;
       /*<<stdlib.js 365 48>>*/ return 1 /*<<stdlib.js 366 0>>*/ }
     /*<<mlString.js 307 0>>*/ function caml_string_compare_aO_(s1_a_,s2_b_)
     {s1_a_.t&
      6&&
       /*<<mlString.js 308 16>>*/ caml_convert_string_to_bytes_p_(s1_a_);
      s2_b_.t&
      6&&
       /*<<mlString.js 309 16>>*/ caml_convert_string_to_bytes_p_(s2_b_);
       /*<<mlString.js 310 2>>*/ return s1_a_.c<s2_b_.c?-1:s1_a_.c>s2_b_.c?1:0 /*<<mlString.js 311 0>>*/ }
     /*<<stdlib.js 281 0>>*/ function caml_compare_val_az_(a_a_,b_b_,total_c_)
     { /*<<stdlib.js 282 12>>*/ var stack_e_=[];
       /*<<stdlib.js 283 2>>*/ for(;;)
        /*<<stdlib.js 283 10>>*/ { /*<<stdlib.js 284 4>>*/ if
         (!(total_c_&&a_a_===b_b_))
          /*<<stdlib.js 284 29>>*/ if(a_a_ instanceof MlString_h_)
           /*<<stdlib.js 285 33>>*/ if(b_b_ instanceof MlString_h_)
           { /*<<stdlib.js 286 35>>*/ if(a_a_!==b_b_)
              /*<<stdlib.js 287 25>>*/ { /*<<stdlib.js 288 8>>*/ var
               x_d_=
                 /*<<stdlib.js 288 10>>*/ caml_string_compare_aO_(a_a_,b_b_);
               /*<<stdlib.js 289 2>>*/ if(x_d_!=0)
                /*<<stdlib.js 289 14>>*/ return x_d_}}
          else
            /*<<stdlib.js 293 10>>*/ return 1;
         else
           /*<<stdlib.js 294 13>>*/ if
           (a_a_ instanceof Array&&a_a_[0]===(a_a_[0]|0))
            /*<<stdlib.js 294 58>>*/ { /*<<stdlib.js 295 15>>*/ var
             ta_f_=
              a_a_[0];
             /*<<stdlib.js 297 8>>*/ if(ta_f_===num_254_V_)ta_f_=0;
             /*<<stdlib.js 299 8>>*/ if(ta_f_===num_250_T_)
              /*<<stdlib.js 299 24>>*/ {a_a_=a_a_[1];
               /*<<stdlib.js 301 10>>*/ continue}
            else
              /*<<stdlib.js 302 15>>*/ if
              (b_b_ instanceof Array&&b_b_[0]===(b_b_[0]|0))
               /*<<stdlib.js 302 60>>*/ { /*<<stdlib.js 303 17>>*/ var
                tb_g_=
                 b_b_[0];
                /*<<stdlib.js 305 10>>*/ if(tb_g_===num_254_V_)tb_g_=0;
                /*<<stdlib.js 307 10>>*/ if(tb_g_===num_250_T_)
                 /*<<stdlib.js 307 26>>*/ {b_b_=b_b_[1];
                  /*<<stdlib.js 309 12>>*/ continue}
               else
                 /*<<stdlib.js 310 17>>*/ if(ta_f_!=tb_g_)
                  /*<<stdlib.js 310 31>>*/ return ta_f_<tb_g_?-1:1;
                else
                  /*<<stdlib.js 312 17>>*/ switch(ta_f_)
                  {case 248:
                     /*<<stdlib.js 316 8>>*/ var
                     x_d_=
                       /*<<stdlib.js 316 10>>*/ caml_int_compare_aD_
                       (a_a_[2],b_b_[2]);
                     /*<<stdlib.js 317 2>>*/ if(x_d_!=0)
                      /*<<stdlib.js 317 14>>*/ return x_d_;
                     /*<<stdlib.js 318 2>>*/ break;
                   case 251:
                     /*<<stdlib.js 320 22>>*/  /*<<stdlib.js 321 16>>*/ caml_invalid_argument_y_
                     ("equal: abstract value");
                   case 255:
                     /*<<stdlib.js 325 8>>*/ var
                     x_d_=
                       /*<<stdlib.js 325 10>>*/ caml_int64_compare_aC_(a_a_,b_b_);
                     /*<<stdlib.js 326 2>>*/ if(x_d_!=0)
                      /*<<stdlib.js 326 14>>*/ return x_d_;
                     /*<<stdlib.js 327 2>>*/ break;
                   default:
                     /*<<stdlib.js 330 14>>*/ if(a_a_.length!=b_b_.length)
                      /*<<stdlib.js 330 40>>*/ return a_a_.length<b_b_.length
                             ?-1
                             :1;
                     /*<<stdlib.js 331 14>>*/ if(a_a_.length>1)
                      /*<<stdlib.js 331 32>>*/ stack_e_.push(a_a_,b_b_,1)}}
             else
               /*<<stdlib.js 335 10>>*/ return 1}
          else
            /*<<stdlib.js 336 13>>*/ if
            (b_b_ instanceof MlString_h_||
             b_b_ instanceof Array&&
             b_b_[0]===
             (b_b_[0]|0))
             /*<<stdlib.js 337 60>>*/ return -1;
           else
             /*<<stdlib.js 339 13>>*/ if
             (typeof a_a_!="number"&&a_a_&&a_a_.compare)
              /*<<stdlib.js 339 57>>*/ return  /*<<stdlib.js 340 15>>*/ a_a_.compare
                     (b_b_,total_c_);
            else
              /*<<stdlib.js 341 13>>*/ { /*<<stdlib.js 342 8>>*/ if(a_a_<b_b_)
                /*<<stdlib.js 342 19>>*/ return -1;
               /*<<stdlib.js 343 8>>*/ if(a_a_>b_b_)
                /*<<stdlib.js 343 19>>*/ return 1;
               /*<<stdlib.js 344 8>>*/ if(a_a_!=b_b_)
                /*<<stdlib.js 344 20>>*/ { /*<<stdlib.js 345 10>>*/ if
                 (!total_c_)
                  /*<<stdlib.js 345 22>>*/ return NaN;
                 /*<<stdlib.js 346 10>>*/ if(a_a_==a_a_)
                  /*<<stdlib.js 346 22>>*/ return 1;
                 /*<<stdlib.js 347 10>>*/ if(b_b_==b_b_)
                  /*<<stdlib.js 347 22>>*/ return -1}}
         /*<<stdlib.js 351 4>>*/ if(stack_e_.length==0)
          /*<<stdlib.js 351 27>>*/ return 0;
         /*<<stdlib.js 352 10>>*/ var
         i_i_=
           /*<<stdlib.js 352 12>>*/ stack_e_.pop();
        b_b_= /*<<stdlib.js 353 8>>*/ stack_e_.pop();
        a_a_= /*<<stdlib.js 354 8>>*/ stack_e_.pop();
         /*<<stdlib.js 355 4>>*/ if(i_i_+1<a_a_.length)
          /*<<stdlib.js 355 26>>*/ stack_e_.push(a_a_,b_b_,i_i_+1);
        a_a_=a_a_[i_i_];
        b_b_=b_b_[i_i_]} /*<<stdlib.js 359 0>>*/ }
     /*<<stdlib.js 369 0>>*/ function caml_equal_Y_(x_a_,y_b_)
     { /*<<stdlib.js 369 29>>*/ return +( /*<<stdlib.js 369 38>>*/ caml_compare_val_az_
               (x_a_,y_b_,false)==
              0) /*<<stdlib.js 369 73>>*/ }
     /*<<mlString.js 80 0>>*/ function caml_utf8_of_utf16_aU_(s_a_)
     { /*<<mlString.js 81 2>>*/ for
       (var
          /*<<mlString.js 81 13>>*/ b_h_=str_e_,
          /*<<mlString.js 81 21>>*/ t_c_=b_h_,
         c_b_,
         d_j_,
          /*<<mlString.js 81 34>>*/ i_d_=0,
          /*<<mlString.js 81 41>>*/ l_i_=s_a_.length;
        i_d_<
        l_i_;
        i_d_++)
        /*<<mlString.js 81 65>>*/ {c_b_=
         /*<<mlString.js 82 8>>*/ s_a_.charCodeAt(i_d_);
         /*<<mlString.js 83 4>>*/ if(c_b_<num_128_f_)
          /*<<mlString.js 83 18>>*/ { /*<<mlString.js 84 6>>*/ for
           ( /*<<mlString.js 84 17>>*/ var j_g_=i_d_+1;
            j_g_<
            l_i_&&
            (c_b_= /*<<mlString.js 84 42>>*/ s_a_.charCodeAt(j_g_))<
            num_128_f_;
            j_g_++)
            /*<<mlString.js 84 71>>*/ ;
           /*<<mlString.js 85 6>>*/ if(j_g_-i_d_>num_512_S_)
            /*<<mlString.js 85 23>>*/ { /*<<mlString.js 85 25>>*/ t_c_.substr
             (0,1);
            b_h_+=t_c_;
            t_c_=str_e_;
            b_h_+= /*<<mlString.js 85 62>>*/ s_a_.slice(i_d_,j_g_)}
          else
           t_c_+= /*<<mlString.js 86 16>>*/ s_a_.slice(i_d_,j_g_);
           /*<<mlString.js 87 6>>*/ if(j_g_==l_i_)
            /*<<mlString.js 87 18>>*/ break;
          i_d_=j_g_}
         /*<<mlString.js 90 4>>*/ if(c_b_<num_2048_P_)
          /*<<mlString.js 90 19>>*/ {t_c_+=
           /*<<mlString.js 91 11>>*/ String.fromCharCode(192|c_b_>>6);
          t_c_+=
           /*<<mlString.js 92 11>>*/ String.fromCharCode(num_128_f_|c_b_&63)}
        else
          /*<<mlString.js 93 11>>*/ if(c_b_<55296||c_b_>=num_57343_Q_)
           /*<<mlString.js 93 42>>*/ t_c_+=
           /*<<mlString.js 94 11>>*/ String.fromCharCode
           (num_224_U_|c_b_>>12,num_128_f_|c_b_>>6&63,num_128_f_|c_b_&63);
         else
           /*<<mlString.js 97 11>>*/ if
           (c_b_>=
            56319||
            i_d_+
            1==
            l_i_||
            (d_j_= /*<<mlString.js 98 20>>*/ s_a_.charCodeAt(i_d_+1))<
            num_56320_N_||
            d_j_>
            num_57343_Q_)
            /*<<mlString.js 98 65>>*/ t_c_+="\xef\xbf\xbd";
          else
            /*<<mlString.js 101 11>>*/ {i_d_++;
            c_b_=(c_b_<<10)+d_j_-56613888;
            t_c_+=
             /*<<mlString.js 104 11>>*/ String.fromCharCode
             (num_240_O_|c_b_>>18,
              num_128_f_|c_b_>>12&63,
              num_128_f_|c_b_>>6&63,
              num_128_f_|c_b_&63)}
         /*<<mlString.js 109 4>>*/ if(t_c_.length>num_1024_m_)
          /*<<mlString.js 109 25>>*/ { /*<<mlString.js 109 26>>*/ t_c_.substr
           (0,1);
          b_h_+=t_c_;
          t_c_=str_e_}}
       /*<<mlString.js 111 2>>*/ return b_h_+t_c_ /*<<mlString.js 112 0>>*/ }
     /*<<mlString.js 285 0>>*/ function caml_js_to_string___(s_a_)
     { /*<<mlString.js 286 10>>*/ var tag_b_=9;
       /*<<mlString.js 287 2>>*/ if
       (! /*<<mlString.js 287 7>>*/ caml_is_ascii_Z_(s_a_))
       tag_b_=8,s_a_= /*<<mlString.js 288 41>>*/ caml_utf8_of_utf16_aU_(s_a_);
       /*<<mlString.js 289 2>>*/ return new
              MlString_h_
              (tag_b_,s_a_,s_a_.length) /*<<mlString.js 290 0>>*/ }
     /*<<stdlib.js 124 0>>*/ function caml_raise_sys_error_i_(msg_a_)
     { /*<<stdlib.js 125 2>>*/ caml_raise_with_string_ab_
       (caml_global_data_g_[2],msg_a_) /*<<stdlib.js 126 0>>*/ }
     /*<<io.js 291 0>>*/ function caml_ml_flush_aE_(oc_a_)
     { /*<<io.js 292 4>>*/ if(!oc_a_.opened)
        /*<<io.js 292 20>>*/ caml_raise_sys_error_i_
        ("Cannot flush a closed channel");
       /*<<io.js 293 4>>*/ if(oc_a_.buffer==str_e_)
        /*<<io.js 293 24>>*/ return 0;
       /*<<io.js 294 4>>*/ if(oc_a_.output)
        /*<<io.js 295 6>>*/ switch(oc_a_.output.length)
        {case 2:
           /*<<io.js 296 14>>*/ oc_a_.output(oc_a_,oc_a_.buffer);
           /*<<io.js 296 38>>*/ break;
         default: /*<<io.js 297 15>>*/ oc_a_.output(oc_a_.buffer)}
      oc_a_.buffer=str_e_;
       /*<<io.js 301 4>>*/ return 0 /*<<io.js 302 0>>*/ }
     /*<<mlString.js 294 0>>*/ function caml_create_string_l_(len_a_)
     { /*<<mlString.js 295 2>>*/ if(len_a_<0)
        /*<<mlString.js 295 15>>*/ caml_invalid_argument_y_("String.create");
       /*<<mlString.js 296 2>>*/ return new
              MlString_h_
              (len_a_?2:9,str_e_,len_a_) /*<<mlString.js 297 0>>*/ }
     /*<<fs.js 47 0>>*/ function MlFile_j_(content_a_)
     {this.data=content_a_ /*<<fs.js 47 46>>*/ }
    MlFile_j_.prototype=
    {truncate:
     function()
      {this.data= /*<<fs.js 49 35>>*/ caml_create_string_l_(0) /*<<fs.js 49 11>>*/ }};
     /*<<mlString.js 403 0>>*/ function caml_ml_string_length_z_(s_a_)
     { /*<<mlString.js 403 36>>*/ return s_a_.l /*<<mlString.js 403 47>>*/ }
     /*<<fs.js 72 0>>*/ function caml_raise_no_such_file_aa_(name_a_)
     {name_a_=
      name_a_ instanceof MlString_h_
       ? /*<<fs.js 73 36>>*/ name_a_.toString()
       :name_a_;
       /*<<fs.js 74 2>>*/ caml_raise_sys_error_i_
       (name_a_+": No such file or directory") /*<<fs.js 75 0>>*/ }
     /*<<fs.js 23 21>>*/ var caml_current_dir_aA_=str_M_;
     /*<<fs.js 86 0>>*/ function caml_make_path_q_(name_a_)
     {name_a_=
      name_a_ instanceof MlString_h_
       ? /*<<fs.js 87 34>>*/ name_a_.toString()
       :name_a_;
       /*<<fs.js 88 2>>*/ if( /*<<fs.js 88 5>>*/ name_a_.charCodeAt(0)!=47)
       name_a_=caml_current_dir_aA_+name_a_;
      var
        /*<<fs.js 90 11>>*/ comp_d_= /*<<fs.js 90 13>>*/ name_a_.split(str_M_),
        /*<<fs.js 91 12>>*/ ncomp_b_=[];
       /*<<fs.js 92 2>>*/ for
       ( /*<<fs.js 92 12>>*/ var i_c_=0;i_c_<comp_d_.length;i_c_++)
        /*<<fs.js 92 36>>*/ switch(comp_d_[i_c_])
        {case "..":
           /*<<fs.js 94 15>>*/ if(ncomp_b_.length>1)
            /*<<fs.js 94 34>>*/ ncomp_b_.pop();
           /*<<fs.js 94 47>>*/ break;
         case ".": /*<<fs.js 95 14>>*/ break;
         case "":
           /*<<fs.js 96 13>>*/ if(ncomp_b_.length==0)
            /*<<fs.js 96 35>>*/ ncomp_b_.push(str_e_);
           /*<<fs.js 96 51>>*/ break;
         default:
           /*<<fs.js 97 13>>*/ ncomp_b_.push(comp_d_[i_c_]);
           /*<<fs.js 97 33>>*/ break}
      ncomp_b_.orig=name_a_;
       /*<<fs.js 101 2>>*/ return ncomp_b_ /*<<fs.js 103 0>>*/ }
     /*<<fs.js 31 0>>*/ function MlDir_k_()
     {this.content={} /*<<fs.js 31 34>>*/ }
    MlDir_k_.prototype=
    {exists:
     function(name_a_)
      { /*<<fs.js 33 24>>*/ return this.content[name_a_]?1:0 /*<<fs.js 33 9>>*/ },
     mk:function(name_a_,c_b_){this.content[name_a_]=c_b_ /*<<fs.js 34 5>>*/ },
     get:
     function(name_a_)
      { /*<<fs.js 35 21>>*/ return this.content[name_a_] /*<<fs.js 35 6>>*/ },
     list:
     function()
      { /*<<fs.js 37 10>>*/ var a_a_=[];
        /*<<fs.js 38 4>>*/ for(var n_b_ in this.content)
         /*<<fs.js 39 6>>*/ a_a_.push(n_b_);
        /*<<fs.js 40 4>>*/ return a_a_ /*<<fs.js 36 7>>*/ },
     remove:
     function(name_a_){delete this.content[name_a_] /*<<fs.js 42 9>>*/ }};
     /*<<fs.js 27 18>>*/ var caml_root_dir_s_=new MlDir_k_();
     /*<<fs.js 28 0>>*/ caml_root_dir_s_.mk(str_e_,new MlDir_k_());
     /*<<fs.js 160 0>>*/ function caml_fs_content_x_(path_a_)
     { /*<<fs.js 161 10>>*/ var dir_b_=caml_root_dir_s_;
       /*<<fs.js 162 2>>*/ for
       ( /*<<fs.js 162 11>>*/ var i_c_=0;i_c_<path_a_.length;i_c_++)
        /*<<fs.js 162 32>>*/ { /*<<fs.js 163 4>>*/ if
         (!(dir_b_.exists&& /*<<fs.js 163 23>>*/ dir_b_.exists(path_a_[i_c_])))
          /*<<fs.js 163 45>>*/ caml_raise_no_such_file_aa_(path_a_.orig);
        dir_b_= /*<<fs.js 164 8>>*/ dir_b_.get(path_a_[i_c_])}
       /*<<fs.js 166 2>>*/ return dir_b_ /*<<fs.js 167 0>>*/ }
     /*<<fs.js 235 0>>*/ function caml_sys_is_directory_aR_(name_a_)
     {var
        /*<<fs.js 236 11>>*/ path_c_=
         /*<<fs.js 236 13>>*/ caml_make_path_q_(name_a_),
        /*<<fs.js 237 10>>*/ dir_b_=
         /*<<fs.js 237 12>>*/ caml_fs_content_x_(path_c_);
       /*<<fs.js 238 2>>*/ return dir_b_ instanceof MlDir_k_?1:0 /*<<fs.js 239 0>>*/ }
     /*<<mlString.js 303 0>>*/ function caml_string_of_array_aP_(a_a_)
     { /*<<mlString.js 303 36>>*/ return new MlString_h_(4,a_a_,a_a_.length) /*<<mlString.js 303 71>>*/ }
     /*<<mlString.js 259 0>>*/ function caml_convert_string_to_array_X_(s_a_)
     {var
        /*<<mlString.js 261 8>>*/ a_c_=new Array(s_a_.l),
        /*<<mlString.js 261 28>>*/ b_e_=s_a_.c,
        /*<<mlString.js 261 37>>*/ l_d_=b_e_.length,
        /*<<mlString.js 261 51>>*/ i_b_=0;
       /*<<mlString.js 262 2>>*/ for(;i_b_<l_d_;i_b_++)
       a_c_[i_b_]= /*<<mlString.js 262 28>>*/ b_e_.charCodeAt(i_b_);
       /*<<mlString.js 263 2>>*/ for(l_d_=s_a_.l;i_b_<l_d_;i_b_++)
       a_c_[i_b_]=0;
      s_a_.c=a_c_;
      s_a_.t=4;
       /*<<mlString.js 266 2>>*/ return a_c_ /*<<mlString.js 267 0>>*/ }
     /*<<mlString.js 271 0>>*/ function caml_array_of_string_aY_(s_a_)
     { /*<<mlString.js 272 2>>*/ if(s_a_.t!=4)
        /*<<mlString.js 272 28>>*/ caml_convert_string_to_array_X_(s_a_);
       /*<<mlString.js 273 2>>*/ return s_a_.c /*<<mlString.js 274 0>>*/ }
     /*<<fs.js 112 0>>*/ function caml_fs_register_aB_(name_a_,content_b_)
     {var
        /*<<fs.js 113 11>>*/ path_f_=
         /*<<fs.js 113 13>>*/ caml_make_path_q_(name_a_),
        /*<<fs.js 114 10>>*/ dir_d_=caml_root_dir_s_;
       /*<<fs.js 115 2>>*/ for
       ( /*<<fs.js 115 11>>*/ var i_g_=0;i_g_<path_f_.length-1;i_g_++)
        /*<<fs.js 115 34>>*/ { /*<<fs.js 116 10>>*/ var d_e_=path_f_[i_g_];
         /*<<fs.js 117 4>>*/ if(! /*<<fs.js 117 9>>*/ dir_d_.exists(d_e_))
          /*<<fs.js 118 6>>*/ dir_d_.mk(d_e_,new MlDir_k_());
        dir_d_= /*<<fs.js 119 10>>*/ dir_d_.get(d_e_);
         /*<<fs.js 120 4>>*/ if(!(dir_d_ instanceof MlDir_k_))
          /*<<fs.js 121 6>>*/ caml_raise_sys_error_i_
          (path_f_.orig+str_file_already_abr_w_)}
       /*<<fs.js 123 8>>*/ var d_e_=path_f_[path_f_.length-1];
       /*<<fs.js 124 2>>*/ if( /*<<fs.js 124 5>>*/ dir_d_.exists(d_e_))
        /*<<fs.js 124 20>>*/ caml_raise_sys_error_i_
        (path_f_.orig+str_file_already_abr_w_);
       /*<<fs.js 125 2>>*/ if(content_b_ instanceof MlDir_k_)
        /*<<fs.js 125 31>>*/ dir_d_.mk(d_e_,content_b_);
      else
        /*<<fs.js 126 7>>*/ if(content_b_ instanceof MlFile_j_)
         /*<<fs.js 126 37>>*/ dir_d_.mk(d_e_,content_b_);
       else
         /*<<fs.js 127 7>>*/ if(content_b_ instanceof MlString_h_)
          /*<<fs.js 127 39>>*/ dir_d_.mk(d_e_,new MlFile_j_(content_b_));
        else
          /*<<fs.js 128 7>>*/ if(content_b_ instanceof Array)
           /*<<fs.js 128 36>>*/ dir_d_.mk
           (d_e_,
            new
             MlFile_j_
             ( /*<<fs.js 128 56>>*/ caml_string_of_array_aP_(content_b_)));
         else
           /*<<fs.js 129 7>>*/ if(content_b_.toString)
            /*<<fs.js 129 28>>*/ dir_d_.mk
            (d_e_,
             new
              MlFile_j_
              ( /*<<fs.js 129 49>>*/ caml_new_string_c_
                ( /*<<fs.js 129 65>>*/ content_b_.toString())));
          else
            /*<<fs.js 130 7>>*/ caml_invalid_argument_y_("caml_fs_register");
       /*<<fs.js 131 2>>*/ return 0 /*<<fs.js 132 0>>*/ }
     /*<<fs.js 171 0>>*/ function caml_sys_file_exists_aQ_(name_a_)
     {var
        /*<<fs.js 172 10>>*/ dir_b_=caml_root_dir_s_,
        /*<<fs.js 173 11>>*/ path_d_=
         /*<<fs.js 173 13>>*/ caml_make_path_q_(name_a_),
       auto_load_e_,
       pos_f_;
       /*<<fs.js 176 2>>*/ for
       ( /*<<fs.js 176 11>>*/ var i_c_=0;i_c_<path_d_.length;i_c_++)
        /*<<fs.js 176 32>>*/ { /*<<fs.js 177 4>>*/ if(dir_b_.auto)
          /*<<fs.js 177 17>>*/ {auto_load_e_=dir_b_.auto;pos_f_=i_c_}
         /*<<fs.js 178 4>>*/ if
         (!(dir_b_.exists&& /*<<fs.js 178 23>>*/ dir_b_.exists(path_d_[i_c_])))
          /*<<fs.js 178 45>>*/ return auto_load_e_
                 ? /*<<fs.js 180 15>>*/ auto_load_e_(path_d_,pos_f_)
                 :0;
        dir_b_= /*<<fs.js 184 8>>*/ dir_b_.get(path_d_[i_c_])}
       /*<<fs.js 186 2>>*/ return 1 /*<<fs.js 187 0>>*/ }
     /*<<io.js 34 0>>*/ function caml_sys_open_internal_n_
     (idx_a_,file_b_,flags_c_)
     { /*<<io.js 35 2>>*/ if(caml_global_data_g_.fds===undefined)
       caml_global_data_g_.fds=new Array();
      flags_c_=flags_c_?flags_c_:{};
       /*<<io.js 37 11>>*/ var info_d_={};
      info_d_.file=file_b_;
      info_d_.offset=
      flags_c_.append
       ? /*<<io.js 39 29>>*/ caml_ml_string_length_z_(file_b_.data)
       :0;
      info_d_.flags=flags_c_;
      caml_global_data_g_.fds[idx_a_]=info_d_;
      caml_global_data_g_.fd_last_idx=idx_a_;
       /*<<io.js 43 2>>*/ return idx_a_ /*<<io.js 44 0>>*/ }
     /*<<io.js 45 0>>*/ function caml_sys_open_aZ_(name_a_,flags_b_,perms_c_)
     { /*<<io.js 46 8>>*/ var f_d_={};
       /*<<io.js 47 2>>*/ while(flags_b_)
        /*<<io.js 47 14>>*/ { /*<<io.js 48 4>>*/ switch(flags_b_[1])
         {case 0:f_d_.rdonly=1; /*<<io.js 49 25>>*/ break;
          case 1:f_d_.wronly=1; /*<<io.js 50 25>>*/ break;
          case 2:f_d_.append=1; /*<<io.js 51 25>>*/ break;
          case 3:f_d_.create=1; /*<<io.js 52 25>>*/ break;
          case 4:f_d_.truncate=1; /*<<io.js 53 27>>*/ break;
          case 5:f_d_.excl=1; /*<<io.js 54 24>>*/ break;
          case 6:f_d_.binary=1; /*<<io.js 55 25>>*/ break;
          case 7:f_d_.text=1; /*<<io.js 56 23>>*/ break;
          case 8:f_d_.nonblock=1; /*<<io.js 57 27>>*/ break
          }
        flags_b_=flags_b_[2]}
      var
        /*<<io.js 61 12>>*/ name2_f_= /*<<io.js 61 14>>*/ name_a_.toString(),
        /*<<io.js 62 11>>*/ path_j_=
         /*<<io.js 62 13>>*/ caml_make_path_q_(name_a_);
       /*<<io.js 63 2>>*/ if(f_d_.rdonly&&f_d_.wronly)
        /*<<io.js 64 4>>*/ caml_raise_sys_error_i_
        (name2_f_+" : flags Open_rdonly and Open_wronly are not compatible");
       /*<<io.js 65 2>>*/ if(f_d_.text&&f_d_.binary)
        /*<<io.js 66 4>>*/ caml_raise_sys_error_i_
        (name2_f_+" : flags Open_text and Open_binary are not compatible");
       /*<<io.js 67 2>>*/ if
       ( /*<<io.js 67 6>>*/ caml_sys_file_exists_aQ_(name_a_))
        /*<<io.js 67 34>>*/ { /*<<io.js 68 4>>*/ if
         ( /*<<io.js 68 8>>*/ caml_sys_is_directory_aR_(name_a_))
          /*<<io.js 68 37>>*/ caml_raise_sys_error_i_
          (name2_f_+" : is a directory");
         /*<<io.js 69 4>>*/ if(f_d_.create&&f_d_.excl)
          /*<<io.js 69 28>>*/ caml_raise_sys_error_i_
          (name2_f_+str_file_already_abr_w_);
        var
          /*<<io.js 70 12>>*/ idx_h_=
          caml_global_data_g_.fd_last_idx?caml_global_data_g_.fd_last_idx:0,
          /*<<io.js 71 13>>*/ file_e_=
           /*<<io.js 71 15>>*/ caml_fs_content_x_(path_j_);
         /*<<io.js 72 4>>*/ if(f_d_.truncate)
          /*<<io.js 72 19>>*/ file_e_.truncate();
         /*<<io.js 73 4>>*/ return  /*<<io.js 73 11>>*/ caml_sys_open_internal_n_
                (idx_h_+1,file_e_,f_d_)}
      else
        /*<<io.js 74 9>>*/ if(f_d_.create)
         /*<<io.js 74 23>>*/ { /*<<io.js 75 12>>*/ var
          idx_h_=
           caml_global_data_g_.fd_last_idx?caml_global_data_g_.fd_last_idx:0;
          /*<<io.js 76 4>>*/ caml_fs_register_aB_
          (name_a_, /*<<io.js 76 26>>*/ caml_create_string_l_(0));
          /*<<io.js 77 13>>*/ var
          file_e_=
            /*<<io.js 77 15>>*/ caml_fs_content_x_(path_j_);
          /*<<io.js 78 4>>*/ return  /*<<io.js 78 11>>*/ caml_sys_open_internal_n_
                 (idx_h_+1,file_e_,f_d_)}
       else
         /*<<io.js 80 7>>*/ caml_raise_no_such_file_aa_(name_a_) /*<<io.js 81 0>>*/ }
     /*<<io.js 82 0>>*/ caml_sys_open_internal_n_
     (0,new MlFile_j_( /*<<io.js 82 36>>*/ caml_create_string_l_(0)));
     /*<<io.js 83 0>>*/ caml_sys_open_internal_n_
     (1,new MlFile_j_( /*<<io.js 83 36>>*/ caml_create_string_l_(0)));
     /*<<io.js 84 0>>*/ caml_sys_open_internal_n_
     (2,new MlFile_j_( /*<<io.js 84 36>>*/ caml_create_string_l_(0)));
     /*<<io.js 147 0>>*/ function caml_ml_open_descriptor_in_aF_(fd_a_)
     { /*<<io.js 148 11>>*/ var data_b_=caml_global_data_g_.fds[fd_a_];
       /*<<io.js 149 2>>*/ if(data_b_.flags.wronly)
        /*<<io.js 149 24>>*/ caml_raise_sys_error_i_
        (str_fd_R_+fd_a_+" is writeonly");
       /*<<io.js 151 2>>*/ return {file:data_b_.file,
              offset:data_b_.offset,
              fd:fd_a_,
              opened:true} /*<<io.js 157 0>>*/ }
     /*<<mlString.js 375 0>>*/ function caml_blit_string_W_
     (s1_a_,i1_b_,s2_c_,i2_d_,len_e_)
     { /*<<mlString.js 376 2>>*/ if(len_e_==0)
        /*<<mlString.js 376 16>>*/ return 0;
       /*<<mlString.js 377 2>>*/ if
       (i2_d_==0&&(len_e_>=s2_c_.l||s2_c_.t==2&&len_e_>=s2_c_.c.length))
        /*<<mlString.js 378 72>>*/ {s2_c_.c=
        s1_a_.t==4
         ? /*<<mlString.js 380 13>>*/ caml_subarray_to_string_A_
           (s1_a_.c,i1_b_,len_e_)
         :i1_b_==0&&s1_a_.c.length==len_e_
           ?s1_a_.c
           : /*<<mlString.js 381 50>>*/ s1_a_.c.substr(i1_b_,len_e_);
        s2_c_.t=s2_c_.c.length==s2_c_.l?0:2}
      else
        /*<<mlString.js 383 9>>*/ if(s2_c_.t==2&&i2_d_==s2_c_.c.length)
         /*<<mlString.js 383 59>>*/ {s2_c_.c+=
         s1_a_.t==4
          ? /*<<mlString.js 385 13>>*/ caml_subarray_to_string_A_
            (s1_a_.c,i1_b_,len_e_)
          :i1_b_==0&&s1_a_.c.length==len_e_
            ?s1_a_.c
            : /*<<mlString.js 386 50>>*/ s1_a_.c.substr(i1_b_,len_e_);
         s2_c_.t=s2_c_.c.length==s2_c_.l?0:2}
       else
         /*<<mlString.js 388 9>>*/ { /*<<mlString.js 389 4>>*/ if(s2_c_.t!=4)
           /*<<mlString.js 389 31>>*/ caml_convert_string_to_array_X_(s2_c_);
         var
           /*<<mlString.js 390 11>>*/ c1_g_=s1_a_.c,
           /*<<mlString.js 390 22>>*/ c2_h_=s2_c_.c;
          /*<<mlString.js 391 4>>*/ if(s1_a_.t==4)
           /*<<mlString.js 392 6>>*/ for
           ( /*<<mlString.js 392 17>>*/ var i_f_=0;i_f_<len_e_;i_f_++)
           c2_h_[i2_d_+i_f_]=c1_g_[i1_b_+i_f_];
         else
           /*<<mlString.js 393 9>>*/ { /*<<mlString.js 394 12>>*/ var
            l_i_=
              /*<<mlString.js 394 14>>*/ Math.min(len_e_,c1_g_.length-i1_b_);
            /*<<mlString.js 395 6>>*/ for
            ( /*<<mlString.js 395 17>>*/ var i_f_=0;i_f_<l_i_;i_f_++)
            c2_h_[i2_d_+i_f_]=
             /*<<mlString.js 395 48>>*/ c1_g_.charCodeAt(i1_b_+i_f_);
            /*<<mlString.js 396 6>>*/ for(;i_f_<len_e_;i_f_++)
            c2_h_[i2_d_+i_f_]=0}}
       /*<<mlString.js 399 2>>*/ return 0 /*<<mlString.js 400 0>>*/ }
     /*<<jslib.js 100 0>>*/ function js_print_stderr_aV_(s_a_)
     { /*<<jslib.js 103 2>>*/ if
       ( /*<<jslib.js 103 5>>*/ s_a_.charCodeAt(s_a_.length-1)==10)
       s_a_= /*<<jslib.js 104 8>>*/ s_a_.substr(0,s_a_.length-1);
       /*<<jslib.js 105 8>>*/ var v_b_=joo_global_object_B_.console;
      v_b_&&v_b_.error&& /*<<jslib.js 106 18>>*/ v_b_.error(s_a_) /*<<jslib.js 107 0>>*/ }
     /*<<jslib.js 91 0>>*/ function js_print_stdout_aW_(s_a_)
     { /*<<jslib.js 94 2>>*/ if
       ( /*<<jslib.js 94 5>>*/ s_a_.charCodeAt(s_a_.length-1)==10)
       s_a_= /*<<jslib.js 95 8>>*/ s_a_.substr(0,s_a_.length-1);
       /*<<jslib.js 96 8>>*/ var v_b_=joo_global_object_B_.console;
      v_b_&&v_b_.log&& /*<<jslib.js 97 17>>*/ v_b_.log(s_a_) /*<<jslib.js 98 0>>*/ }
     /*<<io.js 90 25>>*/ var caml_ml_out_channels_r_=new Array();
     /*<<io.js 108 0>>*/ function caml_std_output_aM_(chan_a_,s_b_)
     {var
        /*<<io.js 109 10>>*/ str_h_=
         /*<<io.js 109 12>>*/ caml_new_string_c_(s_b_),
        /*<<io.js 110 11>>*/ slen_d_=
         /*<<io.js 110 13>>*/ caml_ml_string_length_z_(str_h_),
        /*<<io.js 111 11>>*/ clen_g_=
         /*<<io.js 111 13>>*/ caml_ml_string_length_z_(chan_a_.file.data),
        /*<<io.js 112 13>>*/ offset_f_=chan_a_.offset;
       /*<<io.js 113 2>>*/ if(offset_f_+slen_d_>=clen_g_)
        /*<<io.js 113 28>>*/ { /*<<io.js 114 16>>*/ var
         new_str_e_=
           /*<<io.js 114 18>>*/ caml_create_string_l_(offset_f_+slen_d_);
         /*<<io.js 115 4>>*/ caml_blit_string_W_
         (chan_a_.file.data,0,new_str_e_,0,clen_g_);
         /*<<io.js 116 4>>*/ caml_blit_string_W_
         (str_h_,0,new_str_e_,offset_f_,slen_d_);
        chan_a_.file.data=new_str_e_}
      chan_a_.offset+=slen_d_;
       /*<<io.js 120 2>>*/ return 0 /*<<io.js 121 0>>*/ }
     /*<<io.js 123 0>>*/ function caml_ml_open_descriptor_out_$_(fd_a_)
     {var output_b_;
       /*<<io.js 125 2>>*/ switch(fd_a_)
       {case 1:output_b_=js_print_stdout_aW_; /*<<io.js 126 35>>*/ break;
        case 2:output_b_=js_print_stderr_aV_; /*<<io.js 127 35>>*/ break;
        default:output_b_=caml_std_output_aM_}
       /*<<io.js 130 11>>*/ var data_d_=caml_global_data_g_.fds[fd_a_];
       /*<<io.js 131 2>>*/ if(data_d_.flags.rdonly)
        /*<<io.js 131 24>>*/ caml_raise_sys_error_i_
        (str_fd_R_+fd_a_+" is readonly");
       /*<<io.js 132 14>>*/ var
       channel_c_=
        {file:data_d_.file,
         offset:data_d_.offset,
         fd:fd_a_,
         opened:true,
         buffer:str_e_,
         output:output_b_};
      caml_ml_out_channels_r_[channel_c_.fd]=channel_c_;
       /*<<io.js 142 2>>*/ return channel_c_ /*<<io.js 143 0>>*/ }
     /*<<io.js 94 0>>*/ function caml_ml_out_channels_list_aG_()
     { /*<<io.js 95 8>>*/ var l_a_=0;
       /*<<io.js 96 2>>*/ for(var c_b_ in caml_ml_out_channels_r_)
        /*<<io.js 96 36>>*/ if(caml_ml_out_channels_r_[c_b_].opened)
        l_a_=[0,caml_ml_out_channels_r_[c_b_],l_a_];
       /*<<io.js 100 2>>*/ return l_a_ /*<<io.js 101 0>>*/ }
     /*<<stdlib.js 197 0>>*/ function caml_obj_tag_aI_(x_a_)
     { /*<<stdlib.js 197 28>>*/ return x_a_ instanceof Array
              ?x_a_[0]
              :x_a_ instanceof MlString_h_?252:1e3 /*<<stdlib.js 197 95>>*/ }
     /*<<stdlib.js 96 0>>*/ function caml_register_global_a_(n_a_,v_b_)
     {caml_global_data_g_[n_a_+1]=v_b_ /*<<stdlib.js 96 68>>*/ }
     /*<<stdlib.js 76 22>>*/ var caml_named_values_aH_={};
     /*<<mlString.js 278 0>>*/ function caml_bytes_of_string_ay_(s_a_)
     { /*<<mlString.js 279 2>>*/ if((s_a_.t&6)!=0)
        /*<<mlString.js 279 34>>*/ caml_convert_string_to_bytes_p_(s_a_);
       /*<<mlString.js 280 2>>*/ return s_a_.c /*<<mlString.js 281 0>>*/ }
     /*<<stdlib.js 80 0>>*/ function caml_register_named_value_aL_(nm_a_,v_b_)
     {caml_named_values_aH_
       [ /*<<stdlib.js 81 20>>*/ caml_bytes_of_string_ay_(nm_a_)]=
      v_b_;
       /*<<stdlib.js 82 2>>*/ return 0 /*<<stdlib.js 83 0>>*/ }
     /*<<stdlib.js 983 20>>*/ var caml_oo_last_id_aJ_=0;
     /*<<stdlib.js 984 0>>*/ function caml_set_oo_id_b_(b_a_)
     {b_a_[2]=caml_oo_last_id_aJ_++;
       /*<<stdlib.js 986 2>>*/ return b_a_ /*<<stdlib.js 987 0>>*/ }
     /*<<?>>*/ function caml_call_gen1_v_(fun_a_,var0_b_)
     {return fun_a_.length==1
              ?fun_a_(var0_b_)
              :caml_call_gen_o_(fun_a_,[var0_b_])}
    var _D_=[num_248_d_,caml_new_string_c_("Not_found"),-7];
    caml_register_global_a_
     (11,[num_248_d_,caml_new_string_c_("Undefined_recursive_module"),-12]);
    caml_register_global_a_
     (10,[num_248_d_,caml_new_string_c_("Assert_failure"),-11]);
    caml_register_global_a_
     (9,[num_248_d_,caml_new_string_c_("Sys_blocked_io"),-10]);
    caml_register_global_a_
     (8,[num_248_d_,caml_new_string_c_("Stack_overflow"),-9]);
    caml_register_global_a_
     (7,[num_248_d_,caml_new_string_c_("Match_failure"),-8]);
    caml_register_global_a_(6,_D_);
    caml_register_global_a_
     (5,[num_248_d_,caml_new_string_c_("Division_by_zero"),-6]);
    caml_register_global_a_
     (4,[num_248_d_,caml_new_string_c_("End_of_file"),-5]);
    caml_register_global_a_
     (3,[num_248_d_,caml_new_string_c_("Invalid_argument"),-4]);
    caml_register_global_a_(2,[num_248_d_,caml_new_string_c_("Failure"),-3]);
    caml_register_global_a_(1,[num_248_d_,caml_new_string_c_("Sys_error"),-2]);
    caml_register_global_a_
     (0,[num_248_d_,caml_new_string_c_("Out_of_memory"),-1]);
     /*<<pervasives.ml 24 44>>*/  /*<<pervasives.ml 24 44>>*/ caml_set_oo_id_b_
     ([num_248_d_,caml_new_string_c_("Pervasives.Exit"),0]);
     /*<<pervasives.ml 258 12>>*/  /*<<pervasives.ml 258 12>>*/ caml_ml_open_descriptor_in_aF_
     (0);
     /*<<pervasives.ml 259 13>>*/  /*<<pervasives.ml 259 13>>*/ caml_ml_open_descriptor_out_$_
     (1);
     /*<<pervasives.ml 260 13>>*/  /*<<pervasives.ml 260 13>>*/ caml_ml_open_descriptor_out_$_
     (2);
    var
     _ae_=caml_new_string_c_("Array.Bottom"),
     _af_=caml_new_string_c_("Sys.Break"),
     _ag_=caml_new_string_c_("CamlinternalFormat.Type_mismatch"),
     _al_=caml_new_string_c_("Js.Error"),
     _am_=caml_new_string_c_("jsError"),
     _ar_=caml_new_string_c_("span"),
     _as_=caml_new_string_c_("Dom_html.Canvas_not_available"),
     _au_=caml_new_string_c_("green"),
     _aw_=caml_new_string_c_("red"),
     _ax_=caml_new_string_c_("grey"),
     _av_=caml_new_string_c_("display");
     /*<<pervasives.ml 260 34>>*/ function flush_all_ac_(param_a_)
     { /*<<pervasives.ml 286 2>>*/ function iter_b_(param_a_)
       {var param_b_=param_a_;
         /*<<pervasives.ml 286 17>>*/ for(;;)
         { /*<<pervasives.ml 286 17>>*/ if(param_b_)
           {var _c_=param_b_[2],_d_=param_b_[1];
             /*<<pervasives.ml 288 16>>*/ try
             { /*<<pervasives.ml 288 21>>*/  /*<<pervasives.ml 288 21>>*/ caml_ml_flush_aE_
               (_d_)}
            catch(_f_){}
            var param_b_=_c_;
            continue}
           /*<<pervasives.ml 287 12>>*/ return 0} /*<<pervasives.ml 288 50>>*/ }
       /*<<pervasives.ml 289 32>>*/ return  /*<<pervasives.ml 289 32>>*/ iter_b_
              ( /*<<pervasives.ml 289 10>>*/ caml_ml_out_channels_list_aG_(0)) /*<<pervasives.ml 289 32>>*/ }
     /*<<pervasives.ml 260 34>>*/ function do_at_exit_ad_(param_a_)
     { /*<<pervasives.ml 484 20>>*/ return  /*<<pervasives.ml 484 20>>*/ flush_all_ac_
              (0) /*<<pervasives.ml 484 39>>*/ }
    caml_set_oo_id_b_([num_248_d_,_ae_,0]);
     /*<<sys.ml 29 34>>*/  /*<<sys.ml 29 34>>*/ caml_set_oo_id_b_
     ([num_248_d_,_af_,0]);
    caml_set_oo_id_b_([num_248_d_,_ag_,0]);
    var printers_E_=[0,0];
    function register_printer_F_(fn_a_)
     { /*<<printexc.ml 220 2>>*/ printers_E_[1]=[0,fn_a_,printers_E_[1]];
       /*<<printexc.ml 220 2>>*/ return 0 /*<<printexc.ml 220 29>>*/ }
    var
      /*<<js.ml 50 15>>*/ window_t_=joo_global_object_B_,
      /*<<js.ml 63 28>>*/ undefined_G_=undefined;
    function _ah_(name_a_,exn_b_)
     { /*<<callback.ml 24 27>>*/ var
       exn_c_=
         /*<<callback.ml 24 16>>*/ caml_obj_tag_aI_(exn_b_)===num_248_d_
         ?exn_b_
         :exn_b_[0+1];
       /*<<callback.ml 25 2>>*/ return  /*<<callback.ml 25 2>>*/ caml_register_named_value_aL_
              (name_a_,exn_c_) /*<<callback.ml 25 32>>*/ }
     /*<<js.ml 60 20>>*/ var no_handler_ai_=null;
     /*<<js.ml 63 59>>*/ function _aj_(x_a_,f_b_,g_c_)
     { /*<<js.ml 88 42>>*/ return x_a_==no_handler_ai_
              ? /*<<js.ml 88 48>>*/ caml_call_gen1_v_(f_b_,0)
              : /*<<js.ml 88 58>>*/ caml_call_gen1_v_(g_c_,x_a_) /*<<js.ml 88 61>>*/ }
     /*<<js.ml 63 59>>*/ function _H_(x_a_,f_b_)
     { /*<<js.ml 103 16>>*/ return x_a_===undefined_G_
              ? /*<<js.ml 103 39>>*/ caml_call_gen1_v_(f_b_,0)
              :x_a_ /*<<js.ml 103 50>>*/ }
    var
      /*<<js.ml 134 12>>*/ xcac0d41b_I_=true,
      /*<<js.ml 135 13>>*/ false_J_=false,
      /*<<js.ml 236 24>>*/ xbcb1e9dd_ak_=window_t_.Array,
      /*<<js.ml 346 11>>*/ Error_K_=
       /*<<js.ml 346 11>>*/ caml_set_oo_id_b_([num_248_d_,_al_,0]);
     /*<<js.ml 358 8>>*/  /*<<js.ml 358 8>>*/ _ah_(_am_,[0,Error_K_,{}]);
     /*<<js.ml 409 2>>*/  /*<<js.ml 409 2>>*/ register_printer_F_
     (function(param_a_)
       { /*<<js.ml 410 5>>*/ return param_a_[1]===Error_K_
                ?[0,
                   /*<<js.ml 410 31>>*/ caml_js_to_string___
                   ( /*<<js.ml 410 42>>*/ param_a_[2].toString())]
                :0 /*<<js.ml 410 70>>*/ });
     /*<<js.ml 412 2>>*/  /*<<js.ml 412 2>>*/ register_printer_F_
     (function(xa78544e1_a_)
       { /*<<js.ml 414 40>>*/ return xa78544e1_a_ instanceof xbcb1e9dd_ak_
                ?0
                :[0,
                   /*<<js.ml 415 18>>*/ caml_js_to_string___
                   ( /*<<js.ml 415 29>>*/ xa78544e1_a_.toString())] /*<<js.ml 415 56>>*/ });
     /*<<js.ml 415 57>>*/ function _an_(_a_)
     { /*<<js.ml 417 35>>*/ return _a_ /*<<js.ml 417 46>>*/ }
    function _L_(x18184c07_a_,x32f94eb9_b_)
     { /*<<dom.ml 91 10>>*/  /*<<dom.ml 91 10>>*/ x18184c07_a_.appendChild
       (x32f94eb9_b_);
       /*<<dom.ml 91 10>>*/ return 0 /*<<dom.ml 91 41>>*/ }
     /*<<dom_html.ml 1227 15>>*/ var document_u_=window_t_.document;
     /*<<dom_html.ml 1227 15>>*/ function getElementById_ao_(id_a_)
     { /*<<dom_html.ml 1229 2>>*/ function _b_(pnode_a_)
       { /*<<dom_html.ml 1231 18>>*/ return pnode_a_ /*<<dom_html.ml 1231 23>>*/ }
       /*<<dom_html.ml 1229 2>>*/ function _c_(param_a_)
       { /*<<dom_html.ml 1230 30>>*/ throw _D_ /*<<dom_html.ml 1230 30>>*/ }
       /*<<dom_html.ml 1229 15>>*/ return  /*<<dom_html.ml 1229 15>>*/ _aj_
              ( /*<<dom_html.ml 1229 15>>*/ document_u_.getElementById
                ( /*<<dom_html.ml 1229 2>>*/ id_a_.toString()),
               _c_,
               _b_) /*<<dom_html.ml 1231 24>>*/ }
     /*<<dom_html.ml 1227 15>>*/ function createElement_ap_
     (x18184c07_a_,name_b_)
     { /*<<dom_html.ml 1275 44>>*/ return  /*<<dom_html.ml 1275 44>>*/ x18184c07_a_.createElement
              ( /*<<dom_html.ml 1275 44>>*/ name_b_.toString()) /*<<dom_html.ml 1275 78>>*/ }
     /*<<dom_html.ml 1227 15>>*/ function createSpan_aq_(doc_a_)
     { /*<<dom_html.ml 1381 21>>*/ return  /*<<dom_html.ml 1381 21>>*/ createElement_ap_
              (doc_a_,_ar_) /*<<dom_html.ml 1381 45>>*/ }
     /*<<dom_html.ml 1227 15>>*/  /*<<dom_html.ml 1227 15>>*/ caml_set_oo_id_b_
     ([num_248_d_,_as_,0]);
     /*<<dom_html.ml 1417 23>>*/  /*<<dom_html.ml 1417 7>>*/ _an_
     (window_t_.HTMLElement)===
    undefined_G_;
     /*<<diff.ml 24 11>>*/ var
     x3834112d_at_=
       /*<<diff.ml 24 11>>*/ JsDiff.diffChars("beep boop","beep bop blah");
     /*<<diff.ml 28 9>>*/  /*<<diff.ml 28 9>>*/ x3834112d_at_.forEach
     (function(part_a_,_b_,_c_)
       { /*<<diff.ml 29 2>>*/ function _f_(param_a_)
         { /*<<diff.ml 29 50>>*/ return false_J_ /*<<diff.ml 29 56>>*/ }
         /*<<diff.ml 29 14>>*/ var
         t_g_=
           /*<<diff.ml 29 14>>*/ _H_(part_a_.added,_f_);
         /*<<diff.ml 30 2>>*/ function _h_(param_a_)
         { /*<<diff.ml 30 54>>*/ return false_J_ /*<<diff.ml 30 60>>*/ }
         /*<<diff.ml 30 16>>*/ var
         t_i_=
           /*<<diff.ml 30 16>>*/ _H_(part_a_.removed,_h_);
         /*<<diff.ml 32 24>>*/ if
         ( /*<<diff.ml 32 15>>*/ caml_equal_Y_(t_g_,xcac0d41b_I_))
         var _e_=_au_;
        else
         var
           /*<<diff.ml 33 24>>*/ _j_=
            /*<<diff.ml 33 15>>*/ caml_equal_Y_(t_i_,xcac0d41b_I_)?_aw_:_ax_,
          _e_=_j_;
         /*<<diff.ml 36 13>>*/ var
         span_d_=
           /*<<diff.ml 36 13>>*/ createSpan_aq_(document_u_);
         /*<<diff.ml 37 2>>*/ span_d_.style.color=
         /*<<diff.ml 37 2>>*/ _e_.toString();
         /*<<diff.ml 38 2>>*/  /*<<diff.ml 38 2>>*/ _L_
         (span_d_,
           /*<<diff.ml 38 24>>*/ document_u_.createTextNode(part_a_.value));
         /*<<diff.ml 40 9>>*/  /*<<diff.ml 40 9>>*/ _L_
         ( /*<<diff.ml 39 16>>*/ getElementById_ao_(_av_),span_d_);
         /*<<diff.ml 40 37>>*/ return 0 /*<<diff.ml 40 38>>*/ });
     /*<<std_exit.ml 16 8>>*/  /*<<std_exit.ml 16 8>>*/ do_at_exit_ad_(0);
     /*<<std_exit.ml 16 20>>*/ return /*<<?>>*/ }
  (function(){return this}()));
